spring.application.name=ingredient-spring-boot
spring.datasource.url=jdbc:postgresql://localhost:5432/mini_dish_db
spring.datasource.username=postgres
spring.datasource.password=Linah05122005.
spring.datasource.driver-class-name=org.postgresql.Driver
